[package]
name = "aucont_core"
version = "0.1.0"
authors = ["Andrei Tonkikh <andrei.tonkikh@gmail.com>"]

[build-dependencies]
gcc = "0.3"

[dependencies]
libc = "0.2.39"
num = "0.1.42"
nix = "0.10.0"
